version: '2'
services:
  db:
    image: postgres:9.6.2
  api:
    image: ilkerguller/phoenix:latest
    command: mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
